# Site settings
author: Neel Patel
title: A title
header-img: img/home-bg.png
email: neel@hotmail.com
copyright_name: Neel Patel
description: > # this means to ignore newlines until "baseurl:"
  A subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  neelfx

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
